/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qrQpbndS6jq
 */
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Dashboard() {
  return (
    <div className="flex flex-col md:flex-row min-h-screen bg-gray-100 dark:bg-gray-800">
      <aside className="w-full md:w-64 bg-white dark:bg-gray-900 md:h-screen md:sticky md:top-0 overflow-auto">
        <div className="p-4">
          <h2 className="text-lg font-semibold">Job Categories</h2>
          <ul className="mt-4 space-y-2">
            <li>
              <Checkbox id="category-1" />
              <Label htmlFor="category-1">Software Development</Label>
            </li>
            <li>
              <Checkbox id="category-2" />
              <Label htmlFor="category-2">Design</Label>
            </li>
            <li>
              <Checkbox id="category-3" />
              <Label htmlFor="category-3">Marketing</Label>
            </li>
            <li>
              <Checkbox id="category-4" />
              <Label htmlFor="category-4">Sales</Label>
            </li>
            <li>
              <Checkbox id="category-5" />
              <Label htmlFor="category-5">Customer Support</Label>
            </li>
          </ul>
        </div>
      </aside>
      <main className="flex-1 p-4 md:p-6">
        <div className="flex items-center justify-between mb-6">
          <form className="flex-1 mr-4">
            <Input className="w-full bg-white dark:bg-gray-950" placeholder="Search jobs..." />
            <Button className="sr-only" type="submit">
              Submit
            </Button>
          </form>
          <Button className="flex-none">Create New Job</Button>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <BriefcaseIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Frontend Developer</CardTitle>
                <CardDescription>Acme Inc</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold">Deadline: 30th Jan, 2024</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <BriefcaseIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>UX Designer</CardTitle>
                <CardDescription>XYZ Corp</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold">Deadline: 15th Feb, 2024</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <BriefcaseIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Marketing Manager</CardTitle>
                <CardDescription>ABC Ltd</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold">Deadline: 20th Mar, 2024</div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  )
}
