/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qAbje7l8qwf
 */


export function Loading() {
  return (
    <div className="w-full h-4 bg-gray-200 rounded-lg">
      <div
        className="h-full bg-green-500 rounded-lg"
        style={{
          width: "50%",
        }}
      />
    </div>
  )
}
